version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  
  build:
    commands:
      - AWS_CONNECTION_STRING_SECRET_ARN=arn:aws:secretsmanager:us-east-1:891377136147:secret:best-hack-2024-test-task-be/sqlalchemy-database-uri-mdOYL2
      - SQLALCHEMY_DATABASE_URI=$(aws secretsmanager get-secret-value --secret-id $AWS_CONNECTION_STRING_SECRET_ARN --query SecretString)
      
      - echo Build started on `date`
      - echo Building the Docker image...
      
      - IMAGE_TAG=$(date +%s)   
      
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . --build-arg SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
