from enum import Enum

class ErrorMessageEnum(str, Enum):
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS'
  INVALID_PAYLOAD = 'INVALID_PAYLOAD'
  INVALID_TOKEN = 'INVALID_TOKEN'
  ADVERTISEMENT_NOT_FOUND = 'ADVERTISEMENT_NOT_FOUND'
